import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { FileScan, Sparkles, UserRoundCheck } from "lucide-react";
import { PageIntro, Section, SourceLink } from "@/components/research-ui";
import { Button } from "@/components/ui/button";
import { findings, type Category } from "@/lib/research-data";

export const Route=createFileRoute("/evidence")({head:()=>({meta:[{title:"Evidence Map — MediKiosk Research"},{name:"description",content:"A visual map from Indian healthcare research signals to MediKiosk design decisions."},{property:"og:title",content:"Evidence Map — MediKiosk Research"},{property:"og:description",content:"Indian healthcare evidence mapped to patient case-taking design."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Evidence});

const mapping=[["1.5–9.8 min","Pre-consultation capture"],["53% communication signal","Voice + language"],["64 → 20 → 2","Validated AYUSH structure"],["Fragmented records","Document capture"],["Consent architecture","Controlled exchange"]];
const stages=[{Icon:FileScan,title:"SOURCE"},{Icon:Sparkles,title:"ASSIST"},{Icon:UserRoundCheck,title:"REVIEW"}];

function Evidence(){const [filter,setFilter]=useState<"All"|Category>("All");const visible=findings.filter(f=>filter==="All"||f.category===filter);return <><PageIntro index="06" eyebrow="Evidence" title="Research → design." subtitle="Every decision traces back to evidence."/><Section index="06.1" title="Evidence map"><div className="divide-y divide-border border-y border-border">{mapping.map(([a,b],i)=><div key={a} className="grid items-center gap-4 py-6 md:grid-cols-[3rem_1fr_auto_1fr]"><span className="font-mono text-xs text-muted-foreground">0{i+1}</span><p className="font-mono text-2xl text-accent-foreground">{a}</p><span className="hidden text-2xl text-accent md:block">→</span><p className="font-serif text-3xl">{b}</p></div>)}</div></Section><Section index="06.2" title="Safety chain" dark><div className="grid gap-px bg-primary-foreground/20 md:grid-cols-3">{stages.map(({Icon,title},i)=><div key={title} className="bg-primary p-8"><Icon className="size-8 text-accent"/><p className="mt-12 font-mono text-4xl"><span className="text-accent">0{i+1}</span> {title}</p></div>)}</div><p className="mt-12 text-center font-serif text-5xl lg:text-7xl">AI output ≠ clinical truth.</p></Section><Section index="06.3" title="Filter Indian evidence"><div className="-mx-5 flex gap-2 overflow-x-auto px-5 pb-4">{(["All","Healthcare","AYUSH","Communication"] as const).map(c=><Button key={c} variant={filter===c?"default":"outline"} onClick={()=>setFilter(c)} className="min-h-11 shrink-0">{c}</Button>)}</div><div className="mt-8 grid border-l border-t border-border md:grid-cols-2 xl:grid-cols-3">{visible.map(f=><article key={f.value} className="border-b border-r border-border p-6"><p className="font-mono text-5xl text-accent-foreground">{f.value}</p><p className="mt-3 text-xs font-bold uppercase">{f.label}</p><div className="mt-8"><SourceLink id={f.sourceId} label="Source"/></div></article>)}</div></Section></>}
