import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowUpRight, Building2, BookOpen, FlaskConical, Scale } from "lucide-react";
import { PageIntro, Section } from "@/components/research-ui";
import { sources, type Category, type Credibility } from "@/lib/research-data";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/sources")({head:()=>({meta:[{title:"Research Library — MediKiosk Research"},{name:"description",content:"The official, peer-reviewed and standards sources behind the MediKiosk research experience."},{property:"og:title",content:"The Research Library — MediKiosk Research"},{property:"og:description",content:"Open the evidence behind every research claim."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Sources});
const types:Record<Credibility,typeof Building2>={"OFFICIAL GOVERNMENT":Building2,"PEER-REVIEWED":BookOpen,"SYSTEMATIC REVIEW":FlaskConical,"CLINICAL STUDY":FlaskConical,"STANDARD / GUIDELINE":Scale};
function Sources(){const [filter,setFilter]=useState<"All"|Category>("All");const filtered=sources.filter(s=>filter==="All"||s.categories.includes(filter));const groups=Object.entries(sources.reduce<Record<string,number>>((all,source)=>({...all,[source.studyType]:(all[source.studyType]??0)+1}),{}));return <><PageIntro index="07" eyebrow="Sources" title="The research library" subtitle={`${sources.length} sources. Every claim should lead somewhere a judge can inspect.`}/><Section index="07.0" title="Evidence mix"><div className="grid gap-5 lg:grid-cols-[1fr_2fr]"><div><p className="font-mono text-8xl text-accent-foreground">{sources.length}</p><p className="mt-3 text-xs font-bold uppercase tracking-[0.14em]">inspectable sources</p></div><div className="space-y-4" role="img" aria-label={groups.map(([label,count])=>`${count} ${label}`).join(", ")}>{groups.map(([label,count])=><div key={label} className="grid items-center gap-3 sm:grid-cols-[12rem_1fr_3rem]"><p className="text-[10px] font-bold uppercase">{label}</p><div className="h-9 bg-muted"><div className="h-full bg-primary" style={{width:`${count/sources.length*100}%`}}/></div><p className="font-mono text-2xl text-accent-foreground">{count}</p></div>)}</div></div></Section><Section index="07.1" title="Filter the archive"><div className="-mx-5 flex gap-2 overflow-x-auto px-5 pb-4">{(["All","Healthcare","AYUSH","Digital Health","Communication","Accessibility","AI / Research"] as const).map(c=><Button key={c} variant={filter===c?"default":"outline"} onClick={()=>setFilter(c)} className="min-h-11 shrink-0">{c}</Button>)}</div><p aria-live="polite" className="mt-3 font-mono text-xs text-muted-foreground">Showing {filtered.length} source{filtered.length===1?"":"s"}</p><div className="mt-8 grid gap-4 md:grid-cols-2">{filtered.map(s=>{const Icon=types[s.studyType];return <article key={s.id} className="flex min-h-[310px] flex-col border border-border bg-card p-6"><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.12em] text-accent-foreground"><Icon className="size-4"/>{s.studyType}</span><span className="font-mono text-xs">{s.year}</span></div><h2 className="mt-8 font-serif text-2xl leading-tight">{s.title}</h2><p className="mt-3 text-xs font-bold uppercase tracking-[0.1em] text-muted-foreground">{s.publisher} • {s.country}</p><p className="mt-5 text-sm leading-relaxed text-muted-foreground">{s.matters}</p><a href={s.url} target="_blank" rel="noreferrer" className="mt-auto inline-flex min-h-11 items-end gap-2 pt-6 text-xs font-bold uppercase tracking-[0.12em]">Open source <ArrowUpRight className="size-4"/><span className="sr-only">: {s.title} (opens in new tab)</span></a></article>})}</div></Section></>}
