/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyushRouteImport } from './routes/ayush'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as DigitalHealthRouteImport } from './routes/digital-health'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as PatientsRouteImport } from './routes/patients'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyushRoute = AyushRouteImport.update({
  id: '/ayush',
  path: '/ayush',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalHealthRoute = DigitalHealthRouteImport.update({
  id: '/digital-health',
  path: '/digital-health',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayush': typeof AyushRoute
  '/consultation': typeof ConsultationRoute
  '/digital-health': typeof DigitalHealthRoute
  '/evidence': typeof EvidenceRoute
  '/patients': typeof PatientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayush': typeof AyushRoute
  '/consultation': typeof ConsultationRoute
  '/digital-health': typeof DigitalHealthRoute
  '/evidence': typeof EvidenceRoute
  '/patients': typeof PatientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayush': typeof AyushRoute
  '/consultation': typeof ConsultationRoute
  '/digital-health': typeof DigitalHealthRoute
  '/evidence': typeof EvidenceRoute
  '/patients': typeof PatientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayush'
    | '/consultation'
    | '/digital-health'
    | '/evidence'
    | '/patients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayush'
    | '/consultation'
    | '/digital-health'
    | '/evidence'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/ayush'
    | '/consultation'
    | '/digital-health'
    | '/evidence'
    | '/patients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyushRoute: typeof AyushRoute
  ConsultationRoute: typeof ConsultationRoute
  DigitalHealthRoute: typeof DigitalHealthRoute
  EvidenceRoute: typeof EvidenceRoute
  PatientsRoute: typeof PatientsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayush': {
      id: '/ayush'
      path: '/ayush'
      fullPath: '/ayush'
      preLoaderRoute: typeof AyushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-health': {
      id: '/digital-health'
      path: '/digital-health'
      fullPath: '/digital-health'
      preLoaderRoute: typeof DigitalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyushRoute: AyushRoute,
  ConsultationRoute: ConsultationRoute,
  DigitalHealthRoute: DigitalHealthRoute,
  EvidenceRoute: EvidenceRoute,
  PatientsRoute: PatientsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
